on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: cargo fmt
    steps:
      - uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: true

      - name: cargo fmt
        run: 
          cargo +nightly fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    name: cargo clippy
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: cargo clippy
        run: 
          cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    name: cargo test
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:oibaf/graphics-drivers -y
          sudo apt-get update -y -qq
          sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers

      - name: cargo test --no-run
        run:
          cargo test --no-run

      - name: cargo test
        run: 
          cargo test

      - name: cargo bench --no-run --profile dev
        run:
          cargo bench --no-run --profile dev